#!/usr/bin/env perl

use v5.34.0;
use warnings;

open my $fh, ">", "unzip_generated.go" or die "failed to open: $!";

print $fh <<'END';
// Code generated by generate_unzip.pl; DO NOT EDIT.

package slices

import (
	"github.com/shogo82148/go-container/tuples"
)
END

for my $n(1..64) {
    say $fh "";
    my $types = join ", ", map { "T$_" } 1..$n;
    my $ret_types = join ", ", map { "[]T$_" } 1..$n;
    if ($n > 1) {
        $ret_types = "($ret_types)"
    }
    say $fh "// Unzip$n converts a slice of $n-tuples to slices of each elements.";
    say $fh "func Unzip${n}[$types any](s []tuples.Tuple${n}[$types]) $ret_types {";
    for my $i(1..$n) {
        say $fh "	s$i := make([]T$i, len(s))";
    }
    say $fh "	for i, t := range s {";
    for my $i(1..$n) {
        say $fh "		s${i}[i] = t.V$i";
    }
    say $fh "	}";
    say $fh "	return ", join(", ", map { "s$_" } 1..$n);
    say $fh "}";
}

close($fh);
