#!/usr/bin/env perl

use v5.34.0;
use warnings;

open my $fh, ">", "zip-generated.go" or die "failed to open: $!";

print $fh <<'END';
// Code generated by generate-zip.pl; DO NOT EDIT.

package slices

import (
	"github.com/shogo82148/go-container/tuples"
)
END

for my $n(2..10) {
    say $fh "";
    my $types = join ", ", map { "T$_" } 1..$n;
    my $slice_args = join ", ", map { "s$_ []T$_" } 1..$n;
    my $slices = join ", ", map { "s${_}[i]" } 1..$n;
    say $fh "// Zip$n returns a slice of $n-tuples.";
    say $fh "// The returned slice have the length of the shortest slice.";
    say $fh "func Zip${n}[$types any]($slice_args) []tuples.Tuple${n}[$types] {";
    say $fh "	l := len(s1)";
    for my $i(2..$n) {
        say $fh "	if len(s$i) < l {";
        say $fh "		l = len(s$i)";
        say $fh "	}";
    }
    say $fh "	ret := make([]tuples.Tuple${n}[$types], l)";
    say $fh "	for i := 0; i < l; i++ {";
    say $fh "		ret[i] = tuples.Tuple${n}[$types]{$slices}";
    say $fh "	}";
    say $fh "	return ret";
    say $fh "}";
}

close($fh);
