#!/usr/bin/env perl

use v5.34.0;
use warnings;

open my $fh, ">", "generated.go" or die "failed to open: $!";

print $fh <<'END';
// Code generated by generate.pl; DO NOT EDIT.

package tuples
END

for my $n(2..10) {
    say $fh "";
    my $types = join ", ", map { "T$_" } 1..$n;
    say $fh "// Tuple$n is a $n-tuple.";
    say $fh "type Tuple${n}[$types any] struct {";
    for my $i (1..$n) {
        my $digits = 1;
        if ($n >= 10) {
            $digits = 2;
        }
        printf $fh "\tV%-*d T%d\n", $digits, $i, $i;
    }
    say $fh "}";
    say $fh "";

    my $args = join ", ", map { "v$_ T$_" } 1..$n;
    my $values = join ", ", map { "v$_" } 1..$n;
    say $fh "// New${n} returns a new $n-tuple.";
    say $fh "func New${n}[$types any]($args) Tuple${n}[$types] {";
    say $fh "	return Tuple${n}[$types]{$values}";
    say $fh "}";
}

close($fh);
