#!/usr/bin/env perl

use v5.34.0;
use warnings;

open my $fh, ">", "generated.go" or die "failed to open: $!";

print $fh <<'END';
// Code generated by generate.pl; DO NOT EDIT.

package tuple
END

for my $n(2..10) {
    say $fh "";
    my $types = join ", ", map { "T$_" } 1..$n;
    say $fh "// Tuple$n is a $n-tuple.";
    say $fh "type Tuple${n}[$types any] struct {";
    for my $i (1..$n) {
        my $digits = 1;
        if ($n >= 10) {
            $digits = 2;
        }
        printf $fh "\tV%-*d T%d\n", $digits, $i, $i;
    }
    say $fh "}";
}

close($fh);
