#!/usr/bin/env perl

use v5.34.0;
use warnings;

open my $fh, ">", "unzip_generated.go" or die "failed to open: $!";

print $fh <<'END';
// Code generated by generate_unzip.pl; DO NOT EDIT.

package optional

import (
	"github.com/shogo82148/go-container/tuples"
)
END

for my $n(1..64) {
    say $fh "";
    my $types = join ", ", map { "T$_" } 1..$n;
    my $ret_types = join ", ", map { "Optional[T$_]" } 1..$n;
    if ($n > 1) {
        $ret_types = "($ret_types)"
    }
    say $fh "// Unzip$n returns an optional of $n-tuples.";
    say $fh "func Unzip${n}[$types any](v Optional[tuples.Tuple${n}[$types]]) $ret_types {";
    say $fh "\tif v.valid {";
    if ($n == 1) {
        say $fh "\t\treturn ", join(", ", map { "Optional[T$_]{\n\t\t\tvalue: v.value.V$_,\n\t\t\tvalid: true,\n\t\t}" } 1..$n);
    } else {
        say $fh "\t\treturn ", join(", ", map { "Optional[T$_]{\n\t\t\t\tvalue: v.value.V$_,\n\t\t\t\tvalid: true,\n\t\t\t}" } 1..$n);
    }
    say $fh "\t}";
    say $fh "\treturn ", join(", ", map { "Optional[T$_]{}" } 1..$n);
    say $fh "}";
}

close($fh);
