name: test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go:
          - "1.18.0-beta1"
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: "${{ matrix.go }}"
          stable: ${{ !contains(matrix.go, 'beta') }}
      - uses: actions/checkout@v2
      - name: Test
        run: |
          go test -v -coverprofile=profile.cov ./...
