
   
name: test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: install Go 1.18 beta1
        run: |
          # Currently (2021-12-18), Go 1.18 is pre-release status,
          # and actions/setup-go doesn't support them.
          go install golang.org/dl/go1.18beta1
          go1.18beta1 download
      - uses: actions/checkout@v2
      - name: Test
        run: |
          go1.18beta1 test -v -coverprofile=profile.cov ./...
